name: Matrix Build
on:
  push: 
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: 0 9 * * *
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: windows-latest
            crlf: fix
    runs-on: ${{matrix.os}}
    steps:
      - if: ${{ matrix.crlf }}
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v1
        with:
          version: master

      - run: zig build test