name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the ci-codecov image
      run: docker build . --file ci/Dockerfile --tag ci-codecov:$(date +%s)
    - name: Run the ci-codecov image
      run: docker run --env CODECOV_TOKEN=ae3a67b2-a610-4f81-acd5-1a617c4b10d1 --security-opt seccomp=unconfined -v $(pwd):/source ci-codecov:$(date +%s)
      
