name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and tun the ci-codecov ci-image
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        export tag=ci-codecov:$(date +%s)
        docker build . --file ci/Dockerfile --tag $tag && \
        docker run --env CODECOV_TOKEN=$CODECOV_TOKEN --security-opt seccomp=unconfined -v $(pwd):/source $tag

      
